### ISSUE TITLE
Make Hide Minimap option more explicit 

### ISSUE THREAD

**Issue by Starlynk1** [iraizo/AutoLayer#18]
When the minimap options is checked, it removes the icon. May want to change the wording or invert the function.

Change General Settings 'Minimap Icon' text to 'Hide Minimap Icon' would work.

**Comment by iraizo** [comment]
It already has the text "Show or hide the minimap icon.", you just didn't bother to read but I guess that proves that it must be even more explicit.

Will be changed on the next update.

**Comment by iraizo** [comment]
> But thanks for being rude about people trying to help you out with things.

youre a singular person, not people. You arent helping me out by creating more work instead of just making a PR with the 5 character change you suggested here, either way im very glad you "helped" me out here!

**Comment by Starlynk1** [comment]
Ahh, I see, you're 19 years old and haven't learned how to interact with people. It's not much work to rephrase something not written well. But glad to be helpful to all authors so their addons are useful. Plus the more people you get to use it, the more money you get from Curseforge. So why the whining is beyond me.

**Comment by iraizo** [comment]
>  It's not much work to rephrase something not written well.

which you didn't do and for some reason still give yourself credit for? insane that im supposed to be the one not being able to interact with people

> Plus the more people you get to use it, the more money you get from Curseforge 

I dont get any money from curseforge..?
