### ISSUE TITLE
[Feature Request] Guild Only option

### ISSUE THREAD

**Issue by Starlynk1** [iraizo/AutoLayer#19]
Would like to see a Guild Only option so it limits layer requests to only guild members.

**Comment by iraizo** [comment]
Considering that `GetGuildInfo` only works if the target is in view and with the first look seeing that the only possibilities to actually verify if the player is in our guild or not is to check with `GetGuildRosterInfo` by enumerating over `1..GetNumGuildMembers()` I will have to do some additional research, last resort is caching all members on start and updating regularly by listening to the guild roster change event

**Comment by rodier** [comment]
Well you can just limit it to read layer message from  guild channel isnt??

**Comment by rodier** [comment]
Also please add auto kick after 5 sec :D  from party..

**Comment by iraizo** [comment]
> Well you can just limit it to read layer message from guild channel isnt??

Good point, I forgot about that. If anyone wants to add it before I do on the weekend a simple check for the db setting and checking the channel in `AutoLayer:ProcessMessage` should be enough
