### ISSUE TITLE
Addon Action Blocked

### ISSUE THREAD

**Issue by mootkins** [iraizo/AutoLayer#27]
Had this error pop up

1x [ADDON_ACTION_BLOCKED] AddOn 'AutoLayer_Vanilla' tried to call the protected function 'SecureStateDriverManager:SetAttribute()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `SetAttribute'
[string "@Blizzard_FrameXML/SecureStateDriver.lua"]:18: in function <...rfaceBlizzard_FrameXML/SecureStateDriver.lua:16>
[string "=(tail call)"]: ?
[string "@DragonflightUI/Mixin/StateHandler.mixin.lua"]:132: in function `UpdateStateHandler'
[string "@DragonflightUI/Modules/Buffs.lua"]:476: in function `UpdateBuffState'
[string "@DragonflightUI/Modules/Buffs.lua"]:384: in function `ApplySettings'
[string "@DragonflightUI/Mixin/Modules.mixin.lua"]:69: in function `SetOption'
[string "@DragonflightUI/Modules/Buffs.lua"]:73: in function <DragonflightUI/Modules/Buffs.lua:72>
[string "@DragonflightUI/Modules/Buffs.lua"]:437: in function <DragonflightUI/Modules/Buffs.lua:436>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
}
****

**Comment by iraizo** [comment]
Please disable all addons except autolayer +/buggrabber and try again

**Comment by iraizo** [comment]
Closing as I assume this has nothing to do with AutoLayer.
