### ISSUE TITLE
Addon requesting a password? Can't find it anywhere

### ISSUE THREAD

**Issue by SN682** [iraizo/AutoLayer#28]
Hello, I downloaded AutoLayer through Curseforge, upon /reload in-game, it spams me with an hitbox demanding a password that I cannot remove no matter what unless I disable the addon.

Hitbox message:  **" Please input a password for "layer"  "**

I tried the following;

- Delete settings option in Curseforge
- Reinstall the addon after delete settings
- Version downgrade to 1.4.0

**Comment by iraizo** [comment]
Someone on your realm owns the layer channel and set it with a password, so its unusable until that password is lifted

**Comment by SN682** [comment]
I understand but the addon should'nt spam me if it encounters a password in the channel while I'm not even in the channel nor did I try to join the channel.

**Comment by SN682** [comment]
How is it required? Most people are not even in the channel?

**Comment by iraizo** [comment]
Everyone is in that channel, thats how it works and why it requested it in the first place like you said, its required due to how the addon works, if you want to check it out take a look at layering.lua.
