### ISSUE TITLE
Feature request: make it so you have to layer x number of people before you can request a layer

### ISSUE THREAD

**Issue by bgigurtsis** [iraizo/AutoLayer#31]
Just the title. Encourage community participation by making it a requirement that you have to layer people before you can request a layer from other people. This could be through a ratio system (you have to layer 5 people for every layer you request) or just a flat 'layer 25 people before you can request a layer'.

People could even still request a layer by typing layer in lfg or the layer channel but you could just make the convinience of the button require you to give back.

**Comment by iraizo** [comment]
I don't think this is needed. I've seen this addon pop up in YouTube videos, twitch streamers or while playing on my own where I could get layered by 15+ people at 4 in the morning. 

I also believe most people who know of the existence of the addon (either by getting invited and seeing the whisper, or elsewhere) are capable of realizing that this is a community effort, and it is their choice to contribute or not, I don't think making the software "worse" for those Individuals who don't contribute encourages contribution
