### ISSUE TITLE
configuration for whom to invite

### ISSUE THREAD

**Issue by iraizo** [iraizo/AutoLayer#5]

**Comment by iraizo** [comment]
https://legacy.curseforge.com/wow/addons/autolayer?comment=1

**Comment by Exulion** [comment]
"LF Layer 1/2/3" would be my vote just due to how many people naturally adopt such a format already.

**Comment by iraizo** [comment]
> "LF Layer 1/2/3" would be my vote just due to how many people naturally adopt such a format already.

The new update now implements `LFL 1,2,3` where it requests layers 1,2,3
